# Generated by Django 5.1.2 on 2024-10-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0002_media_artiste_media_auteur_media_fabricant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='fabricant',
            new_name='createur',
        ),
        migrations.AddField(
            model_name='emprunt',
            name='bloque',
            field=models.BooleanField(default=False),
        ),
    ]
